name: shadowsocks-rust
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Rust port of Shadowsocks
description: |
  Shadowsocks Client & Server, written in Rust.

base: core18
grade: devel
confinement: devmode

parts:
  shadowsocks-rust:
    plugin: rust
    source: https://github.com/shadowsocks/shadowsocks-rust.git
