name: shadowsocks-rust
adopt-info: shadowsocks-rust
summary: Rust port of Shadowsocks
description: |
  Shadowsocks Client & Server, written in Rust.
base: core18
grade: devel
confinement: strict

apps:
  ssrust-local:
    command: bin/sslocal
    plugs: [network, network-bind]

  ssrust-local-daemon:
    command: bin/sslocal
    daemon: simple
    plugs: [network, network-bind]

  ssrust-server:
    command: bin/ssserver
    plugs: [network, network-bind]

  ssrust-server-daemon:
    command: bin/ssserver
    daemon: simple
    plugs: [network, network-bind]

  ssrust-url:
    command: bin/ssurl

  ssrust-manager:
    command: bin/ssmanager
    plugs: [network]

passthrough:
  layout:
    /etc/shadowsocks-rust:
      bind: $SNAP_COMMON/etc/shadowsocks-rust

parts:
  shadowsocks-rust:
    plugin: rust
    source: https://github.com/shadowsocks/shadowsocks-rust.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `git describe --tags --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`
