name: shadowsocks-rust
version: "1.11.2"
summary: Rust port of Shadowsocks
description: |
  Shadowsocks Client & Server, written in Rust.

base: core18
grade: devel
confinement: strict

apps:
  ssrust-local:
    command: install/bin/ss-local
    plugs: [network, network-bind]

  ssrust-local-daemon:
    command: install/bin/ss-local
    daemon: simple
    plugs: [network, network-bind]

  ssrust-server:
    command: install/bin/ss-server
    plugs: [network, network-bind]

  ssrust-server-daemon:
    command: install/bin/ss-server
    daemon: simple
    plugs: [network, network-bind]

  ssrust-url:
    command: install/bin/ss-url

  ssrust-manager:
    command: install/bin/ss-manager
    plugs: [network]

passthrough:
  layout:
    /etc/shadowsocks-rust:
      bind: $SNAP_COMMON/etc/shadowsocks-rust

parts:
  shadowsocks-rust:
    plugin: rust
    source: https://github.com/shadowsocks/shadowsocks-rust.git
